spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_engine?useSSL=false&serverTimezone=UTC
    username: root
    password: 1235
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
#    show-sql: true

logging:
  level:
    org.hibernate.type: INFO
#    org.hibernate.type: TRACE

post:
  maxAnnounceSize: 200

blog:
  title: DevPub
  subtitle: Developer Stories
  phone: +7 123 456-78-90
  email: altsora@amatera.su
  copyright: Александр Вергун
  copyrightFrom: 2021