spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_engine?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1235
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
#    show-sql: true

logging:
  level:
    org.hibernate.type: INFO
#    org.hibernate.type: TRACE

post:
  maxAnnounceSize: 200

captcha:
  hours: 2
  minutes: 0
  length: 3
  width: 100
  height: 35
  imageEncoding: data:image/png;base64,
  formatName: png

blog:
  title: Паблик на локалхосте
  subtitle: Истории уровня /b #Developer Stories
  phone: +7 123 456-78-90
  email: altsora@amatera.su
  copyright: Александр Вергун
  copyrightFrom: 2021